version: "3.5"

services:
  app:
    restart: always
    env_file:
      - .env
    image: node:18
    container_name: self-financies-control
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - db

  db:
    container_name: db
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
#   db:
#     image: postgres
#     container_name: self_financies_control_db
#     restart: always
#     ports:
#       - ${DB_PORT}:${DB_PORT}
#     environment:
#       - POSTGRES_PORT=${DB_PORT}
#       - POSTGRES_HOST=${DB_HOST}
#       - POSTGRES_USER=${DB_USER}
#       - POSTGRES_PASSWORD=${DB_PASS}
#       - POSTGRES_DB=${DB_NAME}
#     volumes:
#       - data:/data/postgres
# volumes:
#   data:
#     driver: local

# prisma-studio:
#   container_name: prisma-studio
#   image: timothyjmiller/prisma-studio:latest
#   restart: unless-stopped
#   env_file:
#    - .env
#   depends_on:
#     - db
#   ports:
#     - ${PRISMA_STUDIO_PORT}:5555
